CXX = cl
BUILD = build
CXXFLAGS = /O2 /std:c++17 /W4 -I"..\\.." /D_CRT_SECURE_NO_WARNINGS /D_REENTRANT /Fo"$(BUILD)\\" /EHs-
TARGET = app.exe
SRC = main.cpp

all: $(TARGET)

$(BUILD):
	mkdir $(BUILD)

$(TARGET): $(SRC) ..\..\logger.h $(BUILD)
	$(CXX) $(CXXFLAGS) $(SRC) /Fe:$(BUILD)\$(TARGET)
	move $(BUILD)\$(TARGET) .

clean:
	if exist $(TARGET) del $(TARGET)
	rmdir /S /Q $(BUILD)

.PHONY: all clean
