name: Build Logger Library

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with GCC
        run: make

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logger-linux
          path: build/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with MSVC
        shell: cmd
        run: nmake /f Makefile.win

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logger-windows
          path: build/
